language: python

python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6

addons:
  apt:
    packages:
      # The following as required for netcdf files:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev

install:
    # Install netcdf4-python from github. pip install does not
    # appear to be working:
    - git clone https://github.com/Unidata/netcdf4-python.git
    - cd netcdf4-python
    - python setup.py build
    - python setup.py install
    - cd ..
    - rm -rf netcdf4-python
    # Install the package:
    - pip install -e .[testing,functions,server,tests]

script:
    - flake8
    - py.test -a 'not auth' --cov=src/pydap/
