language: python

python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6

install:
    - pip install --upgrade pip>=8.1
    - pip install -e .[testing,functions,server,tests]

script:
    - flake8
    - py.test -a 'not auth' --cov=src/pydap/
