language: python

python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6

env:
    # All tests:
    - TEST_SUITE="testing"
    # Base pydap:
    - TEST_SUITE="client"
addons:
  apt:
      packages:
      # The following is required for netcdf files:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev

install:
    - pip install --upgrade pip>=8.1
    # Always install 'tests' since this extra includes
    # testing utilities like pytest, etc.
    - pip install -e .[tests,$TEST_SUITE]

script:
    - flake8
    - if [ $TEST_SUITE == "testing" ]; then py.test --cov=src/pydap/; else py.test -a $TEST_SUITE; fi
