language: python

python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
addons:
  apt:
      packages:
      # The following is required for netcdf files:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev
install:
    # Manually installing cython for netcdf4. Might not be required in the future.
    # Only necessary for 2.7 and 3.4.
    - pip install cython
    - pip install -e .[testing,functions,server,tests]

script:
    - flake8
    - py.test --cov=src/pydap/
