Attributes {
    HDF5_ROOT_GROUP {
        HDFEOS {
            ADDITIONAL {
                FILE_ATTRIBUTES {
                }
            }
            POINTS {
                AMSR-2%20Level%202%20Land%20Data {
                    Data {
                        String Dataset "Combined NPD and SCA Output Fields";
                    }
                    Linkage {
                    }
                }
            }
        }
        HDFEOS%20INFORMATION {
            String Dataset "CoreMetadata.0", "StructMetadata.0";
        }
    }
    /HDFEOS/ {
        String HDF5_OBJ_FULLPATH "/HDFEOS/";
    }
    /HDFEOS/ADDITIONAL/ {
        String HDF5_OBJ_FULLPATH "/HDFEOS/ADDITIONAL/";
    }
    /HDFEOS/ADDITIONAL/FILE_ATTRIBUTES/ {
        String HDF5_OBJ_FULLPATH "/HDFEOS/ADDITIONAL/FILE_ATTRIBUTES/";
    }
    /HDFEOS/POINTS/ {
        String HDF5_OBJ_FULLPATH "/HDFEOS/POINTS/";
    }
    /HDFEOS/POINTS/AMSR-2%20Level%202%20Land%20Data/ {
        String HDF5_OBJ_FULLPATH "/HDFEOS/POINTS/AMSR-2 Level 2 Land Data/";
        UInt32 _LevelWritten 1, 0, 0, 0, 0, 0, 0, 0;
    }
    /HDFEOS/POINTS/AMSR-2%20Level%202%20Land%20Data/Data/ {
        String HDF5_OBJ_FULLPATH "/HDFEOS/POINTS/AMSR-2 Level 2 Land Data/Data/";
    }
    /HDFEOS/POINTS/AMSR-2%20Level%202%20Land%20Data/Data/Combined%20NPD%20and%20SCA%20Output%20Fields {
        String HDF5_OBJ_FULLPATH "/HDFEOS/POINTS/AMSR-2 Level 2 Land Data/Data/Combined NPD and SCA Output Fields";
    }
    /HDFEOS/POINTS/AMSR-2%20Level%202%20Land%20Data/Linkage/ {
        String HDF5_OBJ_FULLPATH "/HDFEOS/POINTS/AMSR-2 Level 2 Land Data/Linkage/";
    }
    /HDFEOS%20INFORMATION/ {
        String HDF5_OBJ_FULLPATH "/HDFEOS INFORMATION/";
        String HDFEOSVersion "HDFEOS_5.1.15";
    }
    /HDFEOS%20INFORMATION/CoreMetadata.0 {
        String HDF5_OBJ_FULLPATH "/HDFEOS INFORMATION/CoreMetadata.0";
    }
    /HDFEOS%20INFORMATION/StructMetadata.0 {
        String HDF5_OBJ_FULLPATH "/HDFEOS INFORMATION/StructMetadata.0";
    }
}
